/// <reference types="vite/client" />
VITE_API_KEY=client_01JME87KTV4TV26WN7V5GX7QAC
VITE_CLIENT_SECRET=sk_test_a2V5XzAxSk1FODdLRE1BWlhBOURWUlZWVEdKWkNNLFFPRER3Qk5OOEdwOURQZ1RQdHNzUFlLT3U
VITE_API_AUTH="https://api.workos.com"